server:
  port: 8082
spring:
  application:
    name: image-storage
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/changelog.xml
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/root?schema=public
    pool:
      max-size: 100
      initial-size: 1